// Dates are dynamically generated by default to reduce maintenance.
// They can be overridden via cypress.env.json if needed.

import HomePage from '../../pages/HomePage'
import BookingDetails from '../../pages/BookingDetails'
import { getISODatePlusDays } from '../../support/dateUtils'

describe('Successful Purchase Flow', () => {
    it('should complete a purchase successfully', () => {
        // Visit Ryanair website
        HomePage.visit()

        // Accept cookies
        HomePage.acceptCookiesButton()

        // Select departure and return flights
        HomePage.selectFromToDestinations('Lisbon', 'Madrid')

        HomePage.selectMonth()

        // Select departure and return dates
        const departureDate = Cypress.env('departureDate') || getISODatePlusDays(30)
        const returnDate = Cypress.env('returnDate') || getISODatePlusDays(37)

        HomePage.selectDepartureDate(departureDate).click()
        HomePage.selectReturnDate(returnDate).click()

        // Click on search button
        HomePage.searchButton()

        // Select flights
        BookingDetails.selectDepartureOption()
        BookingDetails.selectReturnOption()

        cy.wait(2000)

        // Choose fare option
        BookingDetails.chooseFareOption()
 
        // Confirm fare selection
        BookingDetails.confirmFareButton()

        // Click on login later
        BookingDetails.loginLater()

        // Fill in passenger details
        BookingDetails.titleInput()
        BookingDetails.firstNameInput('John')
        BookingDetails.lastNameInput('Doe')

        // Continue to next step
        BookingDetails.continueFlowButton()

        // Click on recommended seat button
        BookingDetails.recommendedSeatButton()

        // Click to deny Fast Track option
        BookingDetails.denyFastTrack()

        // Add cabin bags
        BookingDetails.chooseDepartureBag()
        BookingDetails.chooseReturnBag()
        BookingDetails.bagContinueButton()

        // Continue without extras
        BookingDetails.extrasContinueButton()

        // Continue without transport
        BookingDetails.transportContinueButton()

        BookingDetails.validateLoginRequest()
    });
});